### ISSUE TITLE
Panic in MSYS

### ISSUE THREAD

**Issue by im-nefilim** [bgkillas/kalc#1]
I tried to run this in MSYS and it panicked with 
```rust

thread 'main' panicked at 'called 'Result::unwrap()' on an 'Err' value: Os { code: 1, kind: Uncategorized, message: "Função incorreta." }', src/main.rs:692:31

```

**Comment by bgkillas** [comment]
does not look like my issue, report upstream https://github.com/console-rs/console https://github.com/bgkillas/kalc/blob/v0.5.2/src/main.rs#LL692C1-L692C1
