### ISSUE TITLE
0.01 is 1e-2, not 1e-3

### ISSUE THREAD

**Issue by MarkSwanson** [bgkillas/kalc#12]
> .01
1/100
1e-3

Also, if I type 1e-2 kalc gives me back 1e-3:
> 1e-2
1/100
1e-3

In both cases kalc should give me back 1e-2

**Comment by MarkSwanson** [comment]
Another example:
> 1e-2 * 1e-2
1/10000
1e-5

The answer should be 1e-4

**Comment by bgkillas** [comment]
its because '1/10^n' cant be represented in binary so my rounding system rounds it and changes it to a 1 but forgets to fix the exponent what great fun

fixed hopefully in a way that fixes all instances of this 4bd6372

**Comment by MarkSwanson** [comment]
Glad you're havin' fun! :-) hehe
