### ISSUE TITLE
Parenthesis not working as expected

### ISSUE THREAD

**Issue by xero-lib** [bgkillas/kalc#14]
I was using the choose function today when I got an unreachable error, with math I could do by hand.

![image](https://github.com/bgkillas/kalc/assets/54485853/3d2e8ebe-9823-4673-bf2d-6c5c437598e2)

I was wondering if there was a fix for this, or what I could do to help fix this.

**Comment by bgkillas** [comment]
seems fixed in master branch, last release is quite old because i want to actually release a bug free release for once, i have no clue when i will release a new one though

master also has the choose function just like C(12,2)
