### ISSUE TITLE
macOS support

### ISSUE THREAD

**Issue by duoistwo** [bgkillas/kalc#15]
It would be awesome to have kalc on macOS! I can help with testing on Apple silicon versions (and older Intel versions if neccessary).

**Comment by bgkillas** [comment]
sure, right now if you try and build it i assume it will work and you have the prerequisites https://docs.rs/gmp-mpfr-sys/latest/gmp_mpfr_sys/index.html#building-on-macos tell me if that works

however i also need to figure out where to store the files since i have 0 clue how their files are stored

**Comment by baglayan** [comment]
You can store them as `/Users/<username>/.config/kalc/kalc.history` and `/Users/<username>/.config/kalc/kalc.config` (`/Users/<username>` is `~` in macOS too) and so forth. Here's an image of my .config folder as reference: 
<img width="251" alt="Screenshot of baglayan's .config directory in macOS" src="https://github.com/bgkillas/kalc/assets/55799205/f1834096-d383-49ae-8608-8445b433bac4">

**Comment by bgkillas** [comment]
in that case i do not see anything stopping it from working

**Comment by baglayan** [comment]
Yes, it works and passes `cargo test`.

**Comment by bgkillas** [comment]
graphing via gnuplot works fine i assume? if so then ill just make some minor changes to the readme

**Comment by baglayan** [comment]
I installed gnuplot by `brew install gnuplot` command. It appears to be working fine but there are some warning messages printed to kalc output.  
  
<img width="1088" alt="kalc and gnuplot example for x squared" src="https://github.com/bgkillas/kalc/assets/55799205/686eb700-e816-4693-98e3-d7c82fbfac9b">

**Comment by bgkillas** [comment]
i guess you have to run it like ```kalc 2> /dev/null``` annoying but the gnuplot crate doesn't have a way to disable the error messages

**Comment by baglayan** [comment]
Bumping the issue over at gnuplot crate repo. Please let me know if you need any further testing for kalc on macOS.

**Comment by bgkillas** [comment]
lgtm

**Comment by bgkillas** [comment]
i stopped using the crate to fix a few things and have disabled gnuplot from printing
