### ISSUE TITLE
[Improvement] Make it more clear that you are at an input field

### ISSUE THREAD

**Issue by Christopher876** [bgkillas/kalc#2]
Currently, when you launch `kalc`, you get a blinking cursor waiting for input. I think that this is unintuitive since it is hard to know if the program has started and is working, rather than being hung.

I suggest then when waiting for input, there is a symbol like `>` that suggests that the program is waiting for an input. 

Upon startup, I think there should be some banner or something similar to Python so that it is clear that the program has started. This also makes the cli more in line with other clis with a repl and the cli will feel more "complete".

```
~ ❯ python3                                                                                          18:24:47 took 6s 
Python 3.11.3 (main, Apr  5 2023, 15:52:25) [GCC 12.2.1 20230201] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

Another example (albeit a lot longer):
```
~ ❯ gdb                                                                                                      18:28:31 
GNU gdb (GDB) 13.1
Copyright (C) 2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word".
(gdb)
```

I would do a PR for it, but I don't know what message you would upon startup and what character(s) you'd want to use for the prompt.

**Comment by bgkillas** [comment]
i dont aspecially like a prompt for copying purposes, but a banner sounds even worse to me. ill make it a true/false config option with '> ' being prompt

**Comment by Christopher876** [comment]
I understand! I do think the `>` character when waiting will improve usability for others!

**Comment by bgkillas** [comment]
ill create a new release in ~70 min, master has the changes currently
