### ISSUE TITLE
Compiling kalc error

### ISSUE THREAD

**Issue by simona70** [bgkillas/kalc#20]
Compiling kalc v1.3.2 (/home/simona/.cache/yay/kalc/src/kalc-1.3.2)
error[E0716]: temporary value dropped while borrowed
--> src/graph.rs:129:14
|
123 |         let base_dir = if cfg!(unix)
|             -------- borrow later stored here
...
129 |             &dirs::cache_dir().unwrap().to_str().unwrap().to_owned()
|              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ creates a temporary value which is freed while stillin use
130 |         };
|         - temporary value is freed at the end of this statement
|
= note: consider using a `let` binding to create a longer lived value

For more information about this error, try `rustc --explain E0716`.
error: could not compile `kalc` (bin "kalc") due to 1 previous error
Compiling gmp-mpfr-sys v1.6.4
Compiling rug v1.25.0
Compiling kalc v1.3.2 (/home/simona/.cache/yay/kalc/src/kalc-1.3.2)
error[E0716]: temporary value dropped while borrowed
--> src/graph.rs:129:14
|
123 |         let base_dir = if cfg!(unix)
|             -------- borrow later stored here
...
129 |             &dirs::cache_dir().unwrap().to_str().unwrap().to_owned()
|              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ creates a temporary value which is freed while stillin use
130 |         };
|         - temporary value is freed at the end of this statement
|
= note: consider using a `let` binding to create a longer lived value

For more information about this error, try `rustc --explain E0716`.
error: could not compile `kalc` (bin "kalc") due to 1 previous error

**Comment by bgkillas** [comment]
what rust version do you have, think i remember 79 allowing this

**Comment by bgkillas** [comment]
yeah seems to be an issue on >1.79.0, i updated the minimum version, closing this

**Comment by simona70** [comment]
rustup say rustc 1.78.0 (9b00956e5 2024-04-29)
I run rustup update and now it is ok
