### ISSUE TITLE
Feature Request: Specify Rounding Mantissa

### ISSUE THREAD

**Issue by xero-lib** [bgkillas/kalc#21]
Similar to Excel, add an optional parameter to the `round` function to specify how many digits of mantissa to retain after rounding.

```
round(13.25) # performs expected rounding to 13
round(13.25, 1) # rounds to 13.3
```

[Excel reference](https://support.microsoft.com/en-us/office/round-function-c018c5d8-40fb-4053-90b1-b3e7f61a213c), but without being a required parameter.

**Comment by bgkillas** [comment]
sure, for consistency ill do the same for floor,ceil,trunc

**Comment by bgkillas** [comment]
this should respect output base i guess

**Comment by bgkillas** [comment]
59ec63d
