### ISSUE TITLE
When setting variable a second time, the previous variable set is multiplied

### ISSUE THREAD

**Issue by Christopher876** [bgkillas/kalc#3]
Whenever you set a variable a second time, it seems like the program is trying to execute a multiply operation on the previous set value.

```
~ ➜ kalc                                                                                                     08:23:45 
> 2*8
16
> x=2
> 16*x
32
> x=4
8 <-- preview result, goes away when I press enter
> x=6
24 <-- preview result, goes away when I press enter
```

If you press enter after `x=4`, the "8" preview disappears so I don't think this is what is expected. It seems like it is executing `2*4` or whatever I put for the line `x=4`.

**Comment by bgkillas** [comment]
yeah ill set a if statement to make sure there is no output when = sign is present when i get home

**Comment by bgkillas** [comment]
https://github.com/bgkillas/kalc/commit/adfb2639086a7e5558403a6da167dbc083b8bf47
